#!/usr/bin/env python3
"""
Step 3: Use Gemini API to review and improve Python-injected spelling errors.

Parallel async requests for fast throughput.

Usage:
    python augment_errors.py [--input python_injected.jsonl] [--output augmented.jsonl]
    python augment_errors.py --restart  # fresh start
"""

import asyncio
import json
import os
import random
import re
import sys
import time
import argparse
from pathlib import Path

API_KEY = os.environ.get("GOOGLE_API_KEY", "")
MODEL = "gemini-2.0-flash"

PAIRS_PER_REQUEST = 5
MAX_CONCURRENT = 15  # parallel requests

SYSTEM_PROMPT = """You are reviewing spelling error quality for a children's writing dataset. Each pair has a "clean" version and an "errored" version generated by a rule engine.

Your job:
1. Keep errors that look like genuine child misspellings for the given age
2. Replace any garbled or unrecognizable errors with realistic alternatives
3. If the errored text has fewer than 3 word-level errors, add 1-2 subtle ones
4. If it has more than 7, remove the least realistic ones
5. Keep the clean text EXACTLY as given — do not modify it

Do NOT use these overused misspellings: becuz, sed, thot, fone, realy, frend, laft, cot, rite, nite, lite, wuz, hav, giv, luv, cum, sum, wun, dun, enuf

Instead use natural, diverse errors like: switching vowels (receive→recieve), dropping silent letters (knife→nife), simplifying clusters (jumped→jumpt), doubling/singling consonants (running→runing, dining→dinning), homophones (their→there), missing apostrophes, suffix confusion (tion→shun, ous→us).

Output a JSON array of objects with:
- "errored": the improved errored text
- "index": the pair number (1-based)

Output ONLY the JSON array."""


def build_review_prompt(pairs: list[dict]) -> str:
    lines = [f"Review and improve these {len(pairs)} error pairs:\n"]
    for i, pair in enumerate(pairs, 1):
        age_band = pair.get("age_band", "middle")
        age = pair.get("age", 12)
        error_count = pair.get("error_count", 0)
        lines.append(f"Pair {i} (age {age}, {age_band}):")
        lines.append(f"Clean: {pair['clean']}")
        lines.append(f"Errored: {pair['errored']}")
        lines.append(f"Current errors: {error_count}")
        lines.append("")
    lines.append("Output ONLY a JSON array. No other text.")
    return "\n".join(lines)


def parse_json_response(text: str) -> list[dict]:
    """Extract JSON array from API response."""
    text = text.strip()
    text = re.sub(r'^```(?:json)?\s*', '', text)
    text = re.sub(r'\s*```$', '', text)
    text = text.strip()

    try:
        result = json.loads(text)
        if isinstance(result, list):
            return result
    except json.JSONDecodeError:
        pass

    match = re.search(r'\[.*\]', text, re.DOTALL)
    if match:
        try:
            return json.loads(match.group())
        except json.JSONDecodeError:
            pass

    # Fallback: extract individual objects
    results = []
    for m in re.finditer(r'\{[^{}]*"errored"\s*:\s*"[^"]*"[^{}]*\}', text, re.DOTALL):
        try:
            obj = json.loads(m.group())
            if "errored" in obj:
                results.append(obj)
        except json.JSONDecodeError:
            continue
    return results


async def process_batch(client, semaphore, batch_idx, batch, results_queue):
    """Process a single batch with concurrency limiting."""
    async with semaphore:
        prompt = build_review_prompt(batch)

        for attempt in range(3):
            try:
                response = await client.aio.models.generate_content(
                    model=MODEL,
                    contents=prompt,
                    config={
                        "system_instruction": SYSTEM_PROMPT,
                        "temperature": 0.7,
                        "max_output_tokens": 16384,
                    },
                )
                text = response.text or ""
                break
            except Exception as e:
                if "429" in str(e) or "quota" in str(e).lower() or "RESOURCE_EXHAUSTED" in str(e):
                    wait = 5 * (attempt + 1)
                    await asyncio.sleep(wait)
                elif attempt == 2:
                    print(f"  Batch {batch_idx}: FAILED: {e}", flush=True)
                    # Return original pairs as fallback
                    await results_queue.put((batch_idx, batch, None))
                    return
                else:
                    await asyncio.sleep(2)
        else:
            await results_queue.put((batch_idx, batch, None))
            return

        parsed = parse_json_response(text) if text else []
        await results_queue.put((batch_idx, batch, parsed))


async def writer_task(output_path, results_queue, total_batches):
    """Write results as they arrive."""
    done = 0
    augmented = 0
    fallback = 0
    start = time.time()

    with open(output_path, "a") as f:
        while done < total_batches:
            batch_idx, batch, parsed = await results_queue.get()
            done += 1

            for j, pair in enumerate(batch):
                if parsed and j < len(parsed) and "errored" in parsed[j]:
                    errored = parsed[j]["errored"]
                    source = "augmented"
                    augmented += 1
                else:
                    errored = pair["errored"]
                    source = "python_fallback"
                    fallback += 1

                out = {
                    "errored": errored,
                    "clean": pair["clean"],
                    "genre": pair.get("genre", "unknown"),
                    "age_band": pair.get("age_band", "middle"),
                    "age": pair.get("age", 12),
                    "errors": [],
                    "error_count": 0,
                    "source": source,
                }
                f.write(json.dumps(out) + "\n")
            f.flush()

            if done % 25 == 0 or done == total_batches:
                elapsed = time.time() - start
                rate = done / elapsed if elapsed > 0 else 0
                remaining = (total_batches - done) / rate if rate > 0 else 0
                print(f"  [{done}/{total_batches}] augmented={augmented} fallback={fallback} "
                      f"({rate:.1f} batch/s, ~{remaining:.0f}s left)", flush=True)

    return augmented, fallback


async def run(args):
    from google import genai
    client = genai.Client(api_key=API_KEY)

    input_path = Path(args.input)
    output_path = Path(args.output)

    if not input_path.exists():
        print(f"Error: {input_path} not found")
        sys.exit(1)

    # Read input
    all_pairs = []
    with open(input_path) as f:
        for line in f:
            line = line.strip()
            if line:
                all_pairs.append(json.loads(line))

    print(f"Loaded {len(all_pairs)} pairs")

    identity_pairs = [p for p in all_pairs if p.get("is_identity", False)]
    error_pairs = [p for p in all_pairs if not p.get("is_identity", False)]

    print(f"  Error pairs to augment: {len(error_pairs)}")
    print(f"  Identity pairs (pass-through): {len(identity_pairs)}")

    if args.restart and output_path.exists():
        output_path.unlink()

    # Resume support
    already_done = 0
    if output_path.exists() and not args.restart:
        with open(output_path) as f:
            already_done = sum(1 for line in f if line.strip())
        already_done_errors = max(0, already_done - len(identity_pairs))
        if already_done_errors > 0:
            print(f"  Resuming: {already_done_errors} error pairs already processed")
            error_pairs = error_pairs[already_done_errors:]
        else:
            already_done = 0

    # Write identity pairs on fresh start
    if already_done == 0:
        with open(output_path, "w") as f:
            for p in identity_pairs:
                out = {
                    "errored": p["clean"],
                    "clean": p["clean"],
                    "genre": p.get("genre", "unknown"),
                    "age_band": p.get("age_band", "middle"),
                    "age": p.get("age", 12),
                    "errors": [],
                    "error_count": 0,
                    "source": "identity",
                }
                f.write(json.dumps(out) + "\n")
        print(f"Wrote {len(identity_pairs)} identity pairs")

    if not error_pairs:
        print("No error pairs to process!")
        return

    # Build batches
    batches = []
    for i in range(0, len(error_pairs), args.batch_size):
        batches.append(error_pairs[i:i + args.batch_size])

    print(f"Processing {len(error_pairs)} error pairs in {len(batches)} batches "
          f"({MAX_CONCURRENT} concurrent)", flush=True)

    semaphore = asyncio.Semaphore(MAX_CONCURRENT)
    results_queue = asyncio.Queue()

    writer = asyncio.create_task(writer_task(output_path, results_queue, len(batches)))

    tasks = []
    for i, batch in enumerate(batches):
        task = asyncio.create_task(process_batch(client, semaphore, i, batch, results_queue))
        tasks.append(task)

    await asyncio.gather(*tasks)
    augmented, fallback = await writer

    with open(output_path) as f:
        final_count = sum(1 for line in f if line.strip())
    print(f"\nDone! {final_count} total pairs ({augmented} augmented, {fallback} fallback)", flush=True)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", "-i", default="python_injected.jsonl")
    parser.add_argument("--output", "-o", default="augmented.jsonl")
    parser.add_argument("--batch-size", type=int, default=PAIRS_PER_REQUEST)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--restart", action="store_true")
    args = parser.parse_args()
    random.seed(args.seed)
    asyncio.run(run(args))


if __name__ == "__main__":
    main()
